// Vercel build step for the static Mission Control bundle.
// Copies apps/web/public -> ./public (Vercel `outputDirectory`) and writes a
// runtime config.js so the deployed SPA talks to the same-origin /api function
// (or an explicit BINDERY_API_BASE override) instead of localhost.
import * as fs from "node:fs/promises";
import * as path from "node:path";

const src = path.resolve("apps/web/public");
const out = path.resolve("public");

await fs.rm(out, { recursive: true, force: true });
await fs.cp(src, out, { recursive: true });

// Same-origin by default on Vercel; override with BINDERY_API_BASE env var.
const apiBase = process.env.BINDERY_API_BASE ?? "";
const workspace = process.env.BINDERY_WORKSPACE ?? "default";
const config = `// Generated by scripts/build-web.mjs at deploy time. Do not edit by hand.
window.__BINDERY_API_BASE__ = ${JSON.stringify(apiBase)};
window.BINDERY_WORKSPACE = ${JSON.stringify(workspace)};
`;
await fs.writeFile(path.join(out, "config.js"), config);

console.log(`[build-web] staged ${src} -> ${out} (apiBase=${JSON.stringify(apiBase)}, workspace=${workspace})`);
